### ISSUE TITLE
Function props not fired after changed language

### ISSUE THREAD

**Issue by waisimon** [frandiox/reactesse-edge-template#3]
From the [Demo Link](https://reactesse.zable.workers.dev/)

It was fine when I access the default link
![image](https://user-images.githubusercontent.com/26592019/133936383-31a2ce14-5bc1-421a-b2c7-4f7a82448f3d.png)

After changed language, the props data it not return
![image](https://user-images.githubusercontent.com/26592019/133936410-8dbdb3a3-d684-4b0a-bcf6-b1d84a8a5615.png)

**Comment by subhendukundu** [comment]
Facing a similar issue. Props are not being passed to page.

**Comment by frandiox** [comment]
This was fixed in Vitedge 0.18.1

I haven't updated the online demo yet but template should be fixed 👍
