### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by mikecann** [frandiox/reactesse-edge-template#4]
Using this template then `yarn install` then `yarn dev` results in the following error:

![image](https://user-images.githubusercontent.com/215033/141423169-254a88d0-e716-4f21-bec5-ee50d22c0a44.png)

**Comment by mikecann** [comment]
I think its something to do with the `.default` imports in `vite.config.ts`

**Comment by frandiox** [comment]
Hmm yeah, perhaps that dependency was updated and now it doesn't need the `.default`. I'll try to update the template soon.
